### PR TITLE
Add support for installer

### PR DESCRIPTION
**Pull request by neidiom**
fixes https://github.com/systemli/ansible-role-roundcube/issues/31

### CODE REVIEW

**Comment by t2d** [comment]
But when do you actually want to run the installer?

**Comment by t2d** [comment]
I'm not super happy with the way variables are handled. We do have save defaults, which is good. On the other hand, these defaults will delete the installer in the first run and any change to them afterwards will be meaningless. I think, at least, we would have to add is some very clear instructions in the README. Do you agree?
Or we could think about a smarter way and maybe even merge the installer variables into one?

**Comment by neidiom** [comment]
@t2d please review.

**Comment by t2d** [comment]
Thanks. Looks better already. What do you think about also running `Unarchive roundcube` when `roundcube_enable_installer`?
I think we have to assume that it's either the first run and then the unarchive will run anyway or the installer directory was deleted before and we have to re-extract it. Do you agree?

**Comment by neidiom** [comment]
@t2d please review :)

**Comment by t2d** [comment]
Thanks. Lets see how this behaves in deployment and maybe we can even fix #29 with this new variable?

**Pull request merged**
