### PR TITLE
Add support for group

### PR DESCRIPTION
**Pull request by neidiom**

### CODE REVIEW

**Comment by doobry-systemli** [comment]
What's the purpose of this PR? To be able to set the group to `www-data` in order to give the webserver user access to the roundcube installation? Why not set `roundcube_user` to the webserver user instead?

**Comment by neidiom** [comment]
I am installing it under a control panel therefore every website has it's own user and group.

**Comment by neidiom** [comment]
Also php-fpm is by default run with the same user/group. Example

```
drwxr-x--- 13 web17     client1      4096 Jan 23 21:03 roundcubemail-1.6.1
```

`grep 'user\|group' /etc/php/8.1/fpm/pool.d/web17.conf `
```
user = web17
group = client1
```

**Comment by neidiom** [comment]
If default settings are used nothing really changes. This PR just adds extra customizable options.

**Comment by t2d** [comment]
Cool, looks useful for situations like yours.

**Pull request merged**
